---  
rules:
  ecc_rule:
    module_name : Rules.ecc_rule
    class_name : ECCRule
    ecc_error_url: '/api/v1/query?query=nvidiasmi_ecc_error_count%7Btype%3D%22volatile_double%22%7D%3E0'
    alert_job_owners: False # alert all impacted job owners
    dry_run: {{cnf['repair-manager']['ecc_rule']['dry_run']}}

# time to sleep between rule execution (seconds)
rule_wait_time: 10

cluster_name: {{cnf['repair-manager']['cluster_name']}}

