---  
rules:
  ecc_detect_error_rule:
    module_name : rules.ecc_detect_error_rule
    class_name : ECCDetectErrorRule
  ecc_reboot_node_rule:
    module_name: rules.ecc_reboot_node_rule
    class_name: ECCRebootNodeRule

rule_wait_time: 10 # time to sleep between rule execution (seconds)

cluster_name: {{cnf['repair-manager']['cluster_name']}}

domain_name: {{cnf['repair-manager']['domain_name']}}

job_owner_email_domain: {{cnf['repair-manager']['job_owner_email_domain']}}

restore_from_rule_cache_dump: {{cnf['repair-manager']['restore_from_rule_cache_dump']}}
rule_cache_dump: {{cnf['repair-manager']['rule_cache_dump']}}
